<?php

namespace App\Models;

use App\Observers\CategoryObserver;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected  $table = 'categories';

    protected $fillable = [
        'translation_lang', 'translation_of','name','slug','created_at','updated_at','active'
    ];

    public function scopeSelection($q){
        return $q -> select('id','name','translation_lang','translation_of','slug','active');
    }

    public function getActive(){
        return $this->active == 1 ? 'مفعل' : 'غير مفعل';
    }

    //make self relation with default category and other translation languages
    public function translations(){
        return $this->hasMany(self::class,'translation_of');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Category::observe(CategoryObserver::class);
    }
}
